package sysfetch;
import java.io.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.Timer; //for timer so the table can update automatically

/**
 *
 * @author weaver
 */
public class Processes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Processes.class.getName());

    /**
     * Creates new form Processes
     */
    public Processes() {
        initComponents();
        tblProcesses.getTableHeader().setReorderingAllowed(false);
        
        Timer timer = new Timer(1000, e ->{
           updateProcessTable();
        });
        
        timer.start();
    }
    
    public ArrayList<String[]> getProcesses(){
        ArrayList<String[]> list = new ArrayList<>();
        
        try{
            Process p = Runtime.getRuntime().exec(
                new String[]{"bash", "-c", "ps -eo pid,comm,%cpu,%mem --sort=-%cpu --no-headers"}//no headers to remove weird strings in cpu and mem usage
            );
            
            BufferedReader reader = new BufferedReader(
                new InputStreamReader(p.getInputStream())
            );
            String line;
            boolean first = true;
            
            while ((line = reader.readLine()) != null){
                if(first){
                    first = false; //skip header
                    continue;
                }
                
                String[] parts = line.trim().split("\\s+");
                
                if(parts.length == 4){
                    list.add(parts);
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return list;
    }
    
    public void updateProcessTable(){
        DefaultTableModel model = (DefaultTableModel) tblProcesses.getModel();
        model.setRowCount(0);
        
        for(String[] p : getProcesses()){
            model.addRow(new Object[]{
                p[0], //PID
                p[1], //command
                p[2] + "%", //CPU
                p[3] + "%", //MEM
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProcesses = new javax.swing.JTable();
        btnPreviousPage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Processes");

        tblProcesses.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        tblProcesses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Process ID", "Name", "CPU usage", "Memory Usage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProcesses);
        if (tblProcesses.getColumnModel().getColumnCount() > 0) {
            tblProcesses.getColumnModel().getColumn(0).setResizable(false);
            tblProcesses.getColumnModel().getColumn(1).setResizable(false);
            tblProcesses.getColumnModel().getColumn(2).setResizable(false);
            tblProcesses.getColumnModel().getColumn(3).setResizable(false);
        }

        btnPreviousPage.setText("<--");
        btnPreviousPage.addActionListener(this::btnPreviousPageActionPerformed);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPreviousPage)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnPreviousPage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousPageActionPerformed
        Sysfetch2nd NextForm = new Sysfetch2nd();
        NextForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPreviousPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Processes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPreviousPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private javax.swing.JTable tblProcesses;
    // End of variables declaration//GEN-END:variables
}
