/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sysfetch;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Stack; //so we can go back and forth smoothly in between 
import java.util.ArrayList; //for the search function
import javax.swing.JTable;
import javax.swing.JLabel;
import java.awt.Component;
import javax.swing.filechooser.FileSystemView; //for aesthetic
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author weaver
 */
public class Sysfetch2nd extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Sysfetch2nd.class.getName());

    /**
     * Creates new form Sysfetch2nd
     */
    
    Stack<String> history = new Stack();
    
    String currentPath = System.getProperty("user.home");
    public Sysfetch2nd() {
        initComponents();
        
        LoadDir(currentPath);
        
        //SELF EXPLANATORY
        txtPATH.setEnabled(false);
        FileBrowser.getTableHeader().setReorderingAllowed(false);
        FileBrowser.getTableHeader().setResizingAllowed(false);
        
        //MAKE PATH COLUMN INVISIBLE
        FileBrowser.getColumnModel().getColumn(3).setMinWidth(0);
        FileBrowser.getColumnModel().getColumn(3).setMaxWidth(0);
        FileBrowser.getColumnModel().getColumn(3).setWidth(0);
        
        FileBrowser.getColumnModel().getColumn(0).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel label = (JLabel) super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                String name = value.toString();
                File file = new File(currentPath + File.separator + name);

                label.setIcon(FileSystemView.getFileSystemView().getSystemIcon(file));

                return label;
            }
        });
    }
    
    public void search(File dir, String keyword, ArrayList<File> results){
        File[] files = dir.listFiles();
        if(files == null){
            
            return;
        }
        
        for(File f : files){
            if(f.getName().toLowerCase().contains(keyword.toLowerCase())){
                results.add(f);
            }
            
            if(f.isDirectory()){ 
                search(f, keyword, results);
            }
        }
    }
    
    public void LoadDir(String path){
        currentPath = path;
        
        File directory = new File(path);
        File[] files = directory.listFiles();
        if(files == null) return;
        
        DefaultTableModel model = (DefaultTableModel) FileBrowser.getModel();
        model.setRowCount(0);
        
        for(File f : files){
            
            //String name = f.isFile() ? f.getName() : "📁 " + f.getName();
            String name = f.getName();
            String size = f.isFile() ? String.valueOf(f.length()) + " bytes" : "";
            String type = f.isDirectory() ? "Folder" : "File";
            String fullpath = f.getAbsolutePath();
            
            model.addRow(new Object[]{
                name, size, type, fullpath
            });
        }
        
        txtPATH.setText(path);
        
        //DOESNT CHANGE SIZE FOR SOME REASON
        FileBrowser.getColumnModel().getColumn(0).setPreferredWidth(200); //NAME
        FileBrowser.getColumnModel().getColumn(1).setPreferredWidth(1); //SIZE
        FileBrowser.getColumnModel().getColumn(2).setPreferredWidth(3); //TYPE
        FileBrowser.getColumnModel().getColumn(3).setPreferredWidth(1); //PATH
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FileBrowser = new javax.swing.JTable();
        txtPATH = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnPrevDir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(633, 1030));

        FileBrowser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Size", "Type", "Path"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FileBrowser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FileBrowserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FileBrowser);
        if (FileBrowser.getColumnModel().getColumnCount() > 0) {
            FileBrowser.getColumnModel().getColumn(0).setResizable(false);
            FileBrowser.getColumnModel().getColumn(1).setResizable(false);
            FileBrowser.getColumnModel().getColumn(2).setResizable(false);
        }

        txtPATH.setFont(new java.awt.Font("sansserif", 1, 11)); // NOI18N

        txtSearch.setFont(new java.awt.Font("sansserif", 1, 11)); // NOI18N

        jLabel1.setText("Search");

        btnSearch.setText("Find");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnPrevDir.setText("⏎ ");
        btnPrevDir.addActionListener(this::btnPrevDirActionPerformed);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel2.setText("Thunar from temu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPrevDir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPATH, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPATH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSearch)
                    .addComponent(btnPrevDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileBrowserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FileBrowserMouseClicked
        if(evt.getClickCount() == 2){     //2 for double click
            int row = FileBrowser.getSelectedRow();
            if(row == -1) return; //for error handling
            
            //You can use name: String name = FileBrowser.getValueAt(row, 0).toString(); //gets the folder name
            String type = FileBrowser.getValueAt(row, 2).toString(); //gets the folder type
            String fullpath = FileBrowser.getValueAt(row, 3).toString();
            
            if(type.equals("Folder")){
                // like this: String newPath = currentPath + File.separator + name;//if it is folder then we change directory.
                history.push(currentPath);
                LoadDir(fullpath);
            }
        }
    }//GEN-LAST:event_FileBrowserMouseClicked
        boolean SearchMode;
    private void btnPrevDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevDirActionPerformed
        if(SearchMode){
            SearchMode = false;
            LoadDir(currentPath);
            return;
        }
        
        if(!history.isEmpty()){
            String prevPath = history.pop();
            LoadDir(prevPath);
        }
    }//GEN-LAST:event_btnPrevDirActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String text = txtSearch.getText();
        if(!text.isEmpty()){
            String keyword = txtSearch.getText();
            ArrayList<File> results = new ArrayList<>();

            SearchMode = true; //to prevent bug where the back button dont work if theres no result in search

            search(new File(currentPath), keyword, results);
            txtPATH.setText("");
            DefaultTableModel model = (DefaultTableModel) FileBrowser.getModel();
            model.setRowCount(0);

            if(results.isEmpty()){
                //only show one message if theres no output from search
                model.addRow(new Object[]{"No results found", "", "", ""});
            }

            for(File f : results){
                String name = f.getName();
                String size = f.isFile() ? f.length() + " bytes" : "";
                String type = f.isDirectory() ? "Folder" : "File";
                String fullpath = f.getAbsolutePath();

                model.addRow(new Object[]{name, size, type, fullpath});
            }
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Sysfetch2nd().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FileBrowser;
    private javax.swing.JButton btnPrevDir;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPATH;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
